version: '3'

services:

  postgres:
    image: postgres
    container_name: pgsql-enigma
    environment:
      POSTGRES_PASSWORD: asdf
    volumes:
      - pg_enigma:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  pg_enigma:
    driver: local